"use client";
import "./globals.css"; 
import { Toaster } from 'react-hot-toast'
import { AppContextProvider } from "./_connection/contex.jsx";


const metadata = {
  title: "CampusSphere",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html >
      <body id="body"
      >
        <AppContextProvider>
        {children}
        </AppContextProvider>
        <Toaster
            position="top-center"
            reverseOrder = {false}
        /> 
      </body>
    </html>
  );
}
