"use client";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css"; 
import { Toaster } from 'react-hot-toast'
import { AppContextProvider } from "./_connection/contex.jsx";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata = {
  title: "CampusSphere",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppContextProvider>
        {children}
        </AppContextProvider>
        <Toaster
            position="top-center"
            reverseOrder = {false}
        /> 
      </body>
    </html>
  );
}
